# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: android_apk 0.7.0 ruby lib

Gem::Specification.new do |s|
  s.name = "android_apk"
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kyosuke INOUE"]
  s.date = "2015-04-29"
  s.description = "This library can analyze Android APK application package. You can get any information of android apk file."
  s.email = "kyoro@hakamastyle.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "android_apk.gemspec",
    "lib/android_apk.rb",
    "spec/android_apk_spec.rb",
    "spec/mock/BarcodeScanner4.2.apk",
    "spec/mock/UECExpress.apk",
    "spec/mock/dummy.apk",
    "spec/mock/sample.apk",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kyoro/android_apk"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Android APK file analyzer"

  s.specification_version = 4
end

